name: Test, Lint and Build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js}
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Build
      run: |
        npm ci
        npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Build
      run: |
        npm ci
        npm run lint

  build-webpack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Build
      run: |
        npm ci
        npm run webpack

  build-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Build
      run: |
        npm ci
        npm run build
